[en]
name = agent
search_field_label = agent
search_field_placeholder = search in the agent
search_keywords = agent
search_value_too_large = search is too long

[fi]
name = agentti
search_field_label = agentti
search_field_placeholder = etsi agentista
search_keywords = agentti
search_value_too_large = hakutermi on liian pitkä