[en]
name = thread
search_field_label = thread
search_field_placeholder = search in the thread
search_keywords = thread
search_value_too_large = search is too long

properties.title.label = Thread title
properties.title.placeholder = Type the thread title here.
properties.title.error.TOO_LARGE = thread title is too long

custom.messages = Messages:
custom.loading_messages = Loading messages...

custom.no_messages = No messages found.


[fi]
name = ketju
search_field_label = ketju
search_field_placeholder = etsi ketjuista
search_keywords = ketju
search_value_too_large = hakutermi on liian pitkä

properties.title.label = Ketjun otsikko
properties.title.placeholder = Kirjoita ketjun otsikko tähän.
properties.title.error.TOO_LARGE = ketjun otsikko on liian pitkä

custom.messages = Viestit:
custom.loading_messages = Ladataan viestejä...

custom.no_messages = Viestejä ei löydy.
