[en]
name = permission card
search_field_label = permission card
search_field_placeholder = search in the permission card
search_keywords = permission card
search_value_too_large = search is too long

[fi]
name = käyttöoikeuskortti
search_field_label = käyttöoikeuskortti
search_field_placeholder = etsi käyttöoikeuskorteista
search_keywords = käyttöoikeuskortti
search_value_too_large = hakutermi on liian pitkä