[en]
name = permission request
search_field_label = permission request
search_field_placeholder = search in the permission request
search_keywords = permission request
search_value_too_large = search is too long

custom.requests = Requests
custom.no_requests_found = No requests found
custom.loading = Loading...
custom.new_request = New Request
custom.edit_request = Edit Request
custom.edit = Edit
custom.submit = Submit

properties.message.label = Message to reviewer
properties.message.placeholder = Type a message to the reviewer here
properties.message.error.NOT_NULLABLE = missing message content
properties.message.error.TOO_LARGE = message content is too long

properties.approved.label = Approved
properties.approved.description = Approve this user to access the AI demo

[fi]
name = permission request
search_field_label = permission request
search_field_placeholder = search in the permission request
search_keywords = permission request
search_value_too_large = search is too long

custom.requests = Requests
custom.no_requests_found = No requests found
custom.loading = Loading...
custom.new_request = New Request
custom.edit_request = Edit Request
custom.edit = Edit
custom.submit = Submit

properties.message.label = Message to reviewer
properties.message.placeholder = Type a message to the reviewer here
properties.message.error.NOT_NULLABLE = missing message content
properties.message.error.TOO_LARGE = message content is too long

properties.approved.label = Approved
properties.approved.description = Approve this user to access the AI demo