[en]
name = permission request
search_field_label = permission request
search_field_placeholder = search in the permission request
search_keywords = permission request
search_value_too_large = search is too long

custom.no_requests_yet = Unauthorized
custom.no_requests_yet_description = You do not have permission to access the AI demo. Please submit a request to get access.
custom.make_a_request = Make a request
custom.request_pending = Your request is pending review.
custom.request_pending_description = An admin or a teacher will review your request and get back to you.
custom.view_request = View Request

custom.pending = pending
custom.approved = approved

custom.requests = Requests
custom.no_requests_found = No requests found
custom.loading = Loading...
custom.new_request = New Request
custom.edit_request = Edit Request
custom.edit = Edit
custom.submit = Submit

properties.message.label = Message to reviewer
properties.message.placeholder = Type a message to the reviewer here
properties.message.error.NOT_NULLABLE = missing message content
properties.message.error.TOO_LARGE = message content is too long

properties.approved.label = Approved
properties.approved.description = Approve this user to access the AI demo

custom.approved_status = Approved status

[fi]
name = käyttöoikeuspyyntö
search_field_label = käyttöoikeuspyyntö
search_field_placeholder = etsi käyttöoikeuspyynnöistä
search_keywords = käyttöoikeuspyyntö
search_value_too_large = hakutermi on liian pitkä

custom.no_requests_yet = Ei valtuutusta
custom.no_requests_yet_description = Sinulla ei ole oikeutta käyttää AI-demoa. Lähetä pyyntö saadaksesi käyttöoikeuden.
custom.make_a_request = Tee pyyntö
custom.request_pending = Pyyntösi odottaa tarkistusta.
custom.request_pending_description = Ylläpitäjä tai opettaja tarkistaa pyyntösi ja palaa asiaan.
custom.view_request = Näytä pyyntö

custom.requests = Pyynnöt
custom.no_requests_found = Pyyntöjä ei löydy
custom.loading = Ladataan...
custom.new_request = Uusi pyyntö
custom.edit_request = Muokkaa pyyntöä
custom.edit = Muokkaa
custom.submit = Lähetä

custom.pending = odottaa
custom.approved = hyväksytty

properties.message.label = Viesti tarkistajalle
properties.message.placeholder = Kirjoita viesti tarkistajalle tähän
properties.message.error.NOT_NULLABLE = viestin sisältö puuttuu
properties.message.error.TOO_LARGE = viestin sisältö on liian pitkä

properties.approved.label = Hyväksytty
properties.approved.description = Hyväksy tämä käyttäjä käyttämään AI-demoa

custom.approved_status = Hyväksymisstatus